/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"embed"
	"fmt"
	"strconv"
	"strings"
	"time"

	karpenterv1alpha1 "github.com/algo7/karpenter-provider-pve/api/v1alpha1"
)

//go:embed templates/ubuntu/24.04/build.pkr.hcl
var embeddedTemplates embed.FS

// ubuntuTemplate returns the bytes of the embedded Ubuntu Packer template.
// Callers include this file in the Job's mounted ConfigMap so Packer can
// reference it during the build.
func ubuntuTemplate() ([]byte, error) {
	return embeddedTemplates.ReadFile("templates/ubuntu.pkr.hcl")
}

// pkrvarsInput collects everything needed to render a pkrvars file for a
// single PVENodeImage build. The struct is the boundary between "things
// Kubernetes knows" (CR spec, VMID assignment, template name) and "raw
// strings Packer consumes."
type pkrvarsInput struct {
	// Proxmox placement.
	ProxmoxNode    string
	StoragePool    string
	ISOStoragePool string
	NetworkBridge  string

	// Builder VM identity.
	VMID                int32
	TemplateName        string
	TemplateDescription string

	// Distribution.
	DistributionType    string
	DistributionVersion string

	// Content.
	Timezone          string
	ExtraPackages     []string
	SSHAuthorizedKeys []string

	// ISO source — exactly one of (URL + Checksum) or File is non-empty.
	ISOURL      string
	ISOChecksum string
	ISOFile     string
}

// renderPkrvars produces the text of an auto-loaded Packer vars file. The
// output is valid HCL with one assignment per input field. Values are quoted
// appropriately for their types (string, list, number).
//
// This function is the single place where CR field values get translated
// into Packer's syntax. Tests in pkrvars_test.go pin the exact output for
// representative inputs so accidental format changes get caught.
func renderPkrvars(in *pkrvarsInput) string {
	var b strings.Builder

	b.WriteString("# Generated by karpenter-provider-pve. Do not edit.\n\n")

	writeString := func(key, value string) {
		fmt.Fprintf(&b, "%s = %s\n", key, strconv.Quote(value))
	}

	writeNumber := func(key string, value int32) {
		fmt.Fprintf(&b, "%s = %d\n", key, value)
	}

	writeStringList := func(key string, values []string) {
		if len(values) == 0 {
			fmt.Fprintf(&b, "%s = []\n", key)
			return
		}
		fmt.Fprintf(&b, "%s = [\n", key)
		for _, v := range values {
			fmt.Fprintf(&b, "  %s,\n", strconv.Quote(v))
		}
		b.WriteString("]\n")
	}

	// Required placement.
	writeString("proxmox_node", in.ProxmoxNode)
	writeString("storage_pool", in.StoragePool)
	writeString("iso_storage_pool", in.ISOStoragePool)
	writeString("network_bridge", in.NetworkBridge)

	// Builder identity.
	writeNumber("vm_id", in.VMID)
	writeString("template_name", in.TemplateName)
	writeString("template_description", in.TemplateDescription)

	// Distribution.
	writeString("distribution_type", in.DistributionType)
	writeString("distribution_version", in.DistributionVersion)

	// Content.
	writeString("timezone", in.Timezone)
	writeStringList("extra_packages", in.ExtraPackages)
	writeStringList("ssh_authorized_keys", in.SSHAuthorizedKeys)

	// ISO source — emit whichever pair is set.
	writeString("iso_url", in.ISOURL)
	writeString("iso_checksum", in.ISOChecksum)
	writeString("iso_file", in.ISOFile)

	return b.String()
}

// pkrvarsFromImage builds a pkrvarsInput from a PVENodeImage CR's spec plus
// deployment-level context (VMID assignment, template naming).
//
// TODO: integrates this with the Proxmox connection config to choose
// a free VMID dynamically. For now, the caller passes one in.
func pkrvarsFromImage(
	image *karpenterv1alpha1.PVENodeImage,
	vmID int32,
	templateName string,
) (*pkrvarsInput, error) {
	spec := &image.Spec

	// ISOStoragePool falls back to StoragePool per CRD documentation.
	isoPool := spec.BuildConfig.ISOStoragePool
	if isoPool == "" {
		isoPool = spec.BuildConfig.StoragePool
	}

	// Validate timezone parses as an IANA identifier. time.LoadLocation
	// rejects garbage but accepts anything in the system's tzdata.
	timezone := spec.Timezone
	if _, err := time.LoadLocation(timezone); err != nil {
		return nil, fmt.Errorf("spec.timezone %q is not a valid IANA timezone: %w", timezone, err)
	}

	return &pkrvarsInput{
		ProxmoxNode:         spec.BuildConfig.Node,
		StoragePool:         spec.BuildConfig.StoragePool,
		ISOStoragePool:      isoPool,
		NetworkBridge:       spec.BuildConfig.Bridge,
		VMID:                vmID,
		TemplateName:        templateName,
		TemplateDescription: fmt.Sprintf("Built by karpenter-provider-pve for PVENodeImage/%s", image.Name),
		DistributionType:    string(spec.Distribution.Type),
		DistributionVersion: spec.Distribution.Version,
		Timezone:            timezone,
		ExtraPackages:       spec.Packages,
		SSHAuthorizedKeys:   spec.SSHAuthorizedKeys,
		ISOURL:              spec.BaseImage.URL,
		ISOChecksum:         spec.BaseImage.Checksum,
		ISOFile:             spec.BaseImage.ISOFile,
	}, nil
}
