---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - karpenter.algo7.dev
  resources:
  - pvenodeclasses
  - pvenodeimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - karpenter.algo7.dev
  resources:
  - pvenodeclasses/finalizers
  - pvenodeimages/finalizers
  verbs:
  - update
- apiGroups:
  - karpenter.algo7.dev
  resources:
  - pvenodeclasses/status
  - pvenodeimages/status
  verbs:
  - get
  - patch
  - update
